### ISSUE TITLE
Make optional overriding files for Gaufrette storage 

### ISSUE THREAD

**Issue by bilel-noomene** [dustin10/VichUploaderBundle#703] opened 2017-04-19 14:18 UTC
I think it will be interesting to make overriding optional when using Gaufrette storage. Currently, the parameter override is fixed to true in GaufretteStorage  service:
`$filesystem->write($path, file_get_contents($file->getPathname()), true);`

**Comment by garak** [comment] 2017-04-20 15:58
Feel free to propose a PR

**Comment by Koc** [comment] 2017-04-23 15:54
it is may be useful for all storages. Also imho this should be resolved by file namer.

**Comment by Koc** [comment] 2017-05-08 15:56
can be considered as duplicate of #417

**Closed** 2017-05-08 16:25 UTC
Labels: Enhancement
