### ISSUE TITLE
YAML mappings - Fatal Error

### ISSUE THREAD

**Issue by TheRatG** [dustin10/VichUploaderBundle#492] opened 2016-01-05 08:14 UTC
Hello, with symfony 3.0
\Vich\UploaderBundle\Metadata\Driver\YamlDriver::loadMappingFile
YmlParser::parse - need file_get_content first
```
Catchable Fatal Error: Argument 2 passed to Vich\UploaderBundle\Metadata\Driver\YamlDriver::guessClassName() must be of the type array, string given, called in ...vendor/vich/uploader-bundle/Metadata/Driver/YamlDriver.php on line 40 and defined
```

**Comment by K-Phoen** [comment] 2016-01-12 12:51
Looks like it's a duplicate of #490

**Closed by K-Phoen** 2016-01-12 12:51 UTC
