### ISSUE TITLE
How to use php5.6 instead php7

### ISSUE THREAD

**Issue by krysennn** [dustin10/VichUploaderBundle#564] opened 2016-04-28 09:21 UTC
Hello,

I use VichUploaderBundle, and i would use php5.6 and not php7.

composer install:

Problem 1

> Installation request for ocramius/package-versions 1.0.4 -> satisfiable by ocramius/package-versions[1.0.4].
> ocramius/package-versions 1.0.4 requires php ~7.0 -> your PHP version (5.6.20) does not satisfy that requirement.

Problem 2

> Installation request for ocramius/proxy-manager 2.0.1 -> satisfiable by ocramius/proxy-manager[2.0.1].
> ocramius/proxy-manager 2.0.1 requires php ~7.0 -> your PHP version (5.6.20) does not satisfy that requirement.

Problem 3

> ocramius/proxy-manager 2.0.1 requires php ~7.0 -> your PHP version (5.6.20) does not satisfy that requirement.
> vich/uploader-bundle 1.0.1 requires ocramius/proxy-manager ~1.0|~2.0 -> satisfiable by ocramius/proxy-manager[2.0.1].
> Installation request for vich/uploader-bundle 1.0.1 -> satisfiable by vich/uploader-bundle[1.0.1].

Is it possible to fix it ?

Thank you,
Alexis Camilleri

**Comment by soifou** [comment] 2016-05-26 12:45
Hi @krysennn, 

Not a very nice solution but since v1.0.1 is just a minor release just downgrade to version 1.0.0 and run composer update, it should do the trick !

`"vich/uploader-bundle": "1.0"`

```
Updating dependencies (including require-dev)
  - Removing ocramius/package-versions (1.0.4)
  - Removing zendframework/zend-code (3.0.2)
  - Installing zendframework/zend-code (2.6.3)
    Loading from cache

  - Removing ocramius/proxy-manager (2.0.1)
  - Installing ocramius/proxy-manager (1.0.2)
    Loading from cache

  - Removing vich/uploader-bundle (1.0.1)
  - Installing vich/uploader-bundle (1.0.0)
    Loading from cache
```
Strange that nobody else report this annoying problem... We should't have to be forced to change PHP versions because of some requirements of a bundle.

**Comment by K-Phoen** [comment] 2016-05-26 12:52
I can't reproduce the issue (using PHP 5.6.20-0+deb8u1).

Could you paste your composer.json and the entire error message provided by composer?

**Comment by soifou** [comment] 2016-05-26 13:21
Hi @K-Phoen,

This is the diff of my `composer.lock`when I downgrade from 1.0.1 to 1.0.0:
```
             "name": "vich/uploader-bundle",
-            "version": "1.0.1",
+            "version": "1.0.0",
             "source": {
                 "type": "git",
                 "url": "https://github.com/dustin10/VichUploaderBundle.git",
-                "reference": "85300145a610b3a087a1f5de5e2d31dce4556eab"
+                "reference": "d93c32801b863434cc03fed4be871ccf40d65e51"
             },
             "dist": {
                 "type": "zip",
-                "url": "https://api.github.com/repos/dustin10/VichUploaderBundle/zipball/85300145a610b3a087a1f5de5e2d31dce4556eab",
-                "reference": "85300145a610b3a087a1f5de5e2d31dce4556eab",
+                "url": "https://api.github.com/repos/dustin10/VichUploaderBundle/zipball/d93c32801b863434cc03fed4be871ccf40d65e51",
+                "reference": "d93c32801b863434cc03fed4be871ccf40d65e51",
                 "shasum": ""
             },
             "require": {
                 "jms/metadata": "~1.5",
-                "ocramius/proxy-manager": "~1.0|~2.0",
+                "ocramius/proxy-manager": "~1.0",
                 "php": "~5.5|~7.0",
                 "symfony/finder": "~2.0|~3.0",
                 "symfony/framework-bundle": "~2.3|~3.0",
                 "symfony/property-access": "~2.4|~3.0"
             },
             "require-dev": {
-                "doctrine/doctrine-bundle": "~1.6",
-                "doctrine/mongodb-odm": "~1.0",
+                "doctrine/doctrine-bundle": "*",
+                "doctrine/mongodb-odm": "@dev",
                 "doctrine/orm": "~2.2,>=2.2.3",
                 "ext-sqlite3": "*",
-                "knplabs/knp-gaufrette-bundle": "~0.3",
-                "matthiasnoback/symfony-dependency-injection-test": "~0.7",
+                "knplabs/knp-gaufrette-bundle": "dev-master",
+                "matthiasnoback/symfony-dependency-injection-test": "0.*",
                 "mikey179/vfsstream": "~1.0",
-                "oneup/flysystem-bundle": "~1.0",
+                "oneup/flysystem-bundle": "dev-master",
                 "phpunit/phpunit": "~4.0"
```

The interesting part here is the version change for `ocramius/proxy-manager`
```
-                "ocramius/proxy-manager": "~1.0|~2.0",
+                "ocramius/proxy-manager": "~1.0",
```

And when you check the proxy-manager part, you clearly see the PHP requirement change:
```
"name": "ocramius/proxy-manager",
-            "version": "2.0.1",
+            "version": "1.0.2",
             "source": {
                 "type": "git",
                 "url": "https://github.com/Ocramius/ProxyManager.git",
-                "reference": "6c89b7bd6039d8047b1473e2074cb56baa4bc15d"
+                "reference": "57e9272ec0e8deccf09421596e0e2252df440e11"
             },
             "dist": {
                 "type": "zip",
-                "url": "https://api.github.com/repos/Ocramius/ProxyManager/zipball/6c89b7bd6039d8047b1473e2074cb56baa4bc15d",
-                "reference": "6c89b7bd6039d8047b1473e2074cb56baa4bc15d",
+                "url": "https://api.github.com/repos/Ocramius/ProxyManager/zipball/57e9272ec0e8deccf09421596e0e2252df440e11",
+                "reference": "57e9272ec0e8deccf09421596e0e2252df440e11",
                 "shasum": ""
             },
             "require": {
-                "ocramius/package-versions": "^1.0",
-                "php": "~7.0",
-                "zendframework/zend-code": "~3.0"
+                "php": ">=5.3.3",
+                "zendframework/zend-code": ">2.2.5,<3.0"
             },
```

Let me know if you still want my `composer.json` file. The composer error message is the same as stated by @krysennn

**Comment by K-Phoen** [comment] 2016-05-26 13:27
@soifou The composer.json might be useful. Same for a not truncated output of composer :)

**Comment by soifou** [comment] 2016-05-26 13:49
@K-Phoen ,

Ok you win :) the last revision is the working one (php 5.6)

[composer.json](https://gist.github.com/soifou/2bff95b176120176d74d2204b00d5ad4/revisions)
[composer.lock](https://gist.github.com/soifou/03eae724031b6951e6d98018ffebefde/revisions)

**Comment by garak** [comment] 2016-12-28 15:28
Closing because it looks like it's resolved.
Anyway, php 5.6 will be out of active support next week.

**Closed by garak** 2016-12-28 15:28 UTC
Labels: Support
