### ISSUE TITLE
Wrong uri when DirectoryNamer returns '0'

### ISSUE THREAD

**Issue by huynguyen93** [dustin10/VichUploaderBundle#1360] opened 2023-02-12 03:53 UTC
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.21.1
| Symfony version | 6.0
| PHP version     | 8.1

#### Summary

I have a custom DirectoryNamerInterface

```
class UserFileDirectoryNamer implements DirectoryNamerInterface
{
    public function directoryName($object, PropertyMapping $mapping): string
    {
        return '0';
    }
}
```

The files are uploaded to correct folder (/uploads/0/file.txt), but when I get the uri, it's wrong (/uploads/file.txt)

#### How to reproduce

Make a  DirectoryNamer as above

#### Expected behavior

the uri should be correct (/uploads/0/file.txt)

I took a look at `AbstractStorage`, the bug is probably caused by this check
`$path = !empty($dir) ? $dir.'/'.$filename : $filename;`

`!empty('0')` returns `false`;

**Comment by garak** [comment] 2023-02-12 10:29
Duplicate of #1111

**Closed by garak** 2023-02-12 10:29 UTC
