### ISSUE TITLE
[need feedback] issues regarding FileCache with Symfony 5.2 (beta)

### ISSUE THREAD

**Issue by romaricdrigon** [dustin10/VichUploaderBundle#1161] opened 2020-11-05 09:15 UTC
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | yes?
| Bundle version  | 1.15.0
| Symfony version | 5.2.0-BETA3
| PHP version     | 7.4.11

#### Summary

Hello,

I started testing Symfony 5.2.0_BETA3, and i'm hitting a lot this issue:
```
In FileCache.php line 19:                                                 
The directory "/var/www/html/var/cache/prod/vich_uploader" does not exist.  
```

It prevents the boot of the Symfony application, so no web request / no command can be run including `cache:clear` and `cache:warmup`.
Specifically, the issue is thrown by JMS Metadata `FileCache` constructor, which is used by VichUploader as `vich_uploader.metadata.cache.file_cache`. The cache directory should be created by [VichUploaderExtension:registerCacheStrategy()](https://github.com/dustin10/VichUploaderBundle/blob/master/src/DependencyInjection/VichUploaderExtension.php#L131) before, or by the cache warmer, but it is not. 
I suspect something changed in Symfony 5.2 regarding in which order container is compiled / JMS metadata `FileCache`  service is called. I'm still digging through details, but I have the impression creating a folder in the extension is a little bit brittle, and would need to be moved to somewhere else.

#### Current behavior

Container boot is prevented by the following exception:
```
In FileCache.php line 19:                                                 
The directory "/var/www/html/var/cache/prod/vich_uploader" does not exist.  
```

#### How to reproduce

WIP

#### Expected behavior

No crash!

**Comment by romaricdrigon** [comment] 2020-11-05 09:16
May be related to #1151

**Comment by garak** [comment] 2020-11-05 09:18
I'm using bundle with 5.2-beta3 with no problems

**Comment by romaricdrigon** [comment] 2020-11-05 09:21
OK, then it may not be 5.2-related, but to a specific filesystem setup / some kind of race condition. I'm working on a reproducer, but it is quite random so it is complex.

**Comment by danielchodusov** [comment] 2020-11-16 23:40
The same happens to be after upgrading to Symfony 5.2-RC1

**Comment by rogierknoester** [comment] 2020-11-18 23:19
Running into the same issue on 5.2-RC1 and can reproduce in an empty project based on `symfony/skeleton`: https://github.com/rogierknoester/vich-test

Steps:
1. `git clone https://github.com/rogierknoester/vich-test`
2. `cd vich-test`
3. `composer install`
4. `bin/console -e prod` # this runs without any issue
5. `bin/console -e prod cache:clear` # clears as expected
6. `bin/console -e prod` # now throws that the `/vich_uploader` folder doesn't exist in the cache folder


--------

The issue exists in the value of `%kernel.cache_dir%`. During cache-clear in 5.1 this resolves to

`"/Users/rogierknoester/dev/oxfil/var/cache/pro_/vich_uploader"`

and in 5.2 it resolves to

`"/Users/rogierknoester/dev/vich-test/var/cache/prod/vich_uploader"`


This is visible in the `Kernel`:

**5.1**
<img width="833" alt="image" src="https://user-images.githubusercontent.com/4541046/99599326-6d2b0c80-29fb-11eb-8a92-31b4e1b89c22.png">

**5.2**
<img width="799" alt="image" src="https://user-images.githubusercontent.com/4541046/99599346-79af6500-29fb-11eb-9a1f-7b4189cee9c7.png">

It is indeed fixed by configuring in `vich_uploader.yaml`:
```yaml
    metadata:
        file_cache:
            dir: '%kernel.build_dir%/vich_uploader'
```


Not sure if this is a breaking change of 5.2 or not, it also seems like the `CacheWarmer` does not use the given warmup directory. However, using that parameter means losing some flexibility for configuring the cache, so I'd say the default configuration needs to use `%kernel.build_dir%/vich_uploader`. For example, if you had used 
```yaml
    metadata:
        file_cache:
            dir: '/tmp/%kernel.environment%/vich_uploader'
```
It would work fine too, meaning some people might not have encountered this issue.

**Comment by garak** [comment] 2020-11-19 07:30
It's a tricky situation...
I tried your project, and after downgraded to 5.1 and re-upgraded to 5.2, it works.
A project of mine (upgraded from 5.1 to 5.2) is online without problems (with the correct directory in cache).

The culprit is 5.2 for sure since the "build_dir" parameter didn't exist until 5.1.
Likely, we need to add some check during directory generation for parameter existance

**Comment by romaricdrigon** [comment] 2020-11-23 17:31
Using `%kernel.build_dir%/vich_uploader` fixes the issue on 5.2-RC2. Thank you for your investigation @rogierknoester 
I think indeed `CacheWarmer` should use that parameter (if available).

**Comment by bobvandevijver** [comment] 2020-11-30 11:03
I experience the same issue on Symfony 5.2, but for me it is only caused when the `cache:clear` command is run twice, as that removed the cache folder. See https://github.com/symfony/symfony/issues/39232 for more information.

**Comment by vic-blt** [comment] 2020-12-02 16:16
I also experience this issue when I run `bin/console`.
At line 19 of `vendor/jms/metadata/src/Cache/FileCache.php`:  
```                                                 
The directory "/srv/weekend/var/cache/prod/vich_uploader" does not exist.
```
Symfony: 5.2.0
VichUploaderBundle: 1.15.0

**Comment by OlivierToussaint** [comment] 2020-12-06 15:41
thank you @rogierknoester with sf 5.2 the fix of vich_uploader.yaml works fine

**Comment by fd6130** [comment] 2020-12-07 05:48
For my case, i have no error for `cache:clear` command. But i do have an error when trying to access any controller route `The directory "/var/www/html/var/cache/dev/vich_uploader" does not exist.`

**Comment by tristanbes** [comment] 2020-12-09 12:26
Related to https://github.com/symfony/symfony/issues/39232

**Comment by digitaltim-de** [comment] 2020-12-13 16:46
Same problem and cant fix it

**Comment by bobvandevijver** [comment] 2020-12-15 09:27
This should be solved in Symfony 5.2.1 and higher (thanks to https://github.com/symfony/symfony/pull/39360).

**Comment by garak** [comment] 2020-12-20 17:42
Can someone confirm if upgrading to 5.2.1 is solving?

**Comment by bobvandevijver** [comment] 2020-12-20 18:08
It does for me :+1:

**Comment by fd6130** [comment] 2020-12-21 03:14
I think it is solved after upgrading to 5.2.1

**Comment by garak** [comment] 2020-12-21 08:00
Thank you for feedbacks, I'm closing then.

**Closed by garak** 2020-12-21 08:00 UTC
Labels: Bug

**Comment by bobvandevijver** [comment] 2020-12-21 19:08
Note that for the actual vendor code that caused the error a PR is open as well: https://github.com/schmittjoh/metadata/pull/96. Let's hope that's merged and released before Symfony breaks it again: and to be fair, a cache should recreate the directory anyways :)
