### ISSUE TITLE
delete_on_update and delete_on_remove not working when we customize namer

### ISSUE THREAD

**Issue by sokphea-chea** [dustin10/VichUploaderBundle#553] opened 2016-04-02 01:35 UTC
## entities:

```
/**
 * @Vich\UploadableField(mapping="upload_files", fileNameProperty="drivingLicensePicture")
 *
 * @var File $file
 */
private $drivingLicensePictureFile;

/**
 * @var string
 * @ORM\Column(type="text", nullable=true)
 * @Groups({"list", "license"})
 */
private $drivingLicensePicture;
```
## config:

```
vich_uploader:
    db_driver: orm
    mappings:
            upload_files:
                    uri_prefix:  /
                    upload_destination: %kernel.root_dir%/../web/files
                    namer:              namer.upload_files
                    inject_on_load:     true
                    delete_on_update:   true
                    delete_on_remove:   true
```
## service:

```
namer.upload_files:
    class: AdminBundle\Service\Namer\Namer
    arguments: ['@service_container']
    tags:
        - { name: namer }
```
## my customize namer class :

```php
<?php
namespace AdminBundle\Service\Namer;

use Vich\UploaderBundle\Naming\NamerInterface;
use Vich\UploaderBundle\Mapping\PropertyMapping;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Routing\Router;

/**
* Namer class.
  */
  class Namer implements NamerInterface
  {
  private $container;
  
  public function __construct($container)
  {
      $this->container = $container;
  }
  
  /**
  * Creates a name for the file being uploaded.
    *
  * @param object $obj The object the upload is attached to.
  * @return string The file name.
    */
    function name($obj, PropertyMapping $mapping)
    {
    $mapping = $this->getMapping($obj, $fieldName);
    dump($mapping);die;
    
    $file = $mapping->getFile($obj);
    $newName = uniqid();
    
    if ($extension = $file->guessExtension()) {
        $newName = sprintf('%s.%s', $newName, $extension);
    }
    
    return $this->concatenateFullPath($newName);
    }
  
  private function concatenateFullPath($newName)
  {
      return $this->container->get('request')->getSchemeAndHttpHost() .
          $this->container->getParameter('upload_files_path') .
          $newName;
  }
 }
```  

  I can customize namer to save to database like http://localhost:9501/files/56fe4f717b637.jpeg , but I no longer use auto delete_on_upload and delete_on_remove. The process is working fine but instead of replace the file it's add it up.  If you have any solution on this please suggest? thanks

**Comment by Rikijs** [comment] 2016-04-23 11:47
I wanted to implement custom namer but had error
`Compile Error: Declaration of AdminBundle\Service\Namer\Namer::name() must be compatible with Vich\UploaderBundle\Naming\NamerInterface::name($object, Vich\UploaderBundle\Mapping\PropertyMapping $mapping)`
same as you in this thread: https://github.com/dustin10/VichUploaderBundle/issues/20#issuecomment-204240372

and tried your code,
form renders fine, 
but I get error message:
`Fatal error: Call to undefined method AppBundle\Namer\Namer::getMapping()`
`500 Internal Server Error`
in the line:
`$mapping = $this->getMapping($obj, $fieldName);`

Any suggestions?
Thanks

**Comment by Rikijs** [comment] 2016-04-24 10:18
I found the answer, this code works:
```
    public function name($obj, PropertyMapping $mapping)
    {
        $file = $mapping->getFile($obj);

        $newName = $this->generateRandomSecret();

        if ($extension = $file->guessExtension())
        {
            $newName = $newName .'.'. $extension;
        }

        return $newName;
    }

**Comment by garak** [comment] 2016-12-28 10:12
I guess the problem could be caused by the use of a full path. You should avoid it and save only the name of the file

**Comment by garak** [comment] 2017-01-04 11:51
Closing for missing feedback.

**Closed** 2017-01-05 17:10 UTC
Labels: Support

**Comment by xorgxx** [comment] 2017-03-09 06:59
hi, i have also some probleme it das not delete on update ?
my config : 
```
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        medication_image:
            uri_prefix:         /member/zne
            directory_namer:    app.directory_namer.user
            upload_destination: '%kernel.root_dir%/../web/member/zne'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
```
my li

```
<?php


    namespace Zne\ProfileBundle\Controller\Services;

    use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
    use Symfony\Component\Filesystem\Filesystem;
    use Vich\UploaderBundle\Naming\DirectoryNamerInterface;
    use Vich\UploaderBundle\Mapping\PropertyMapping;

    use Member\UserBundle\Controller\Services\UserServices;
    use Zne\ProfileBundle\Entity\Medication;
    use Zne\ProfileBundle\Entity\Pathology;
    use Zne\ProfileBundle\Entity\Profile;


    class ZneProfileVichDirectoryNamerServices implements DirectoryNamerInterface
    {

        /**
         * @var UserServices
         */
        private $userServices;


        /**
         * UserServices constructor.
         *
         * @param UserServices $userServices
         */
        public function  __construct( UserServices $userServices )
        {
            $this->userServices             = $userServices;
        }

        /**
         * Returns the name of a directory where files will be uploaded
         *
         * Directory name is formed based on user ID and media type
         *
         * @param object          $object
         * @param PropertyMapping $mapping
         *
         * @return string
         */
        public function directoryName($object, PropertyMapping $mapping )
        {
            $userId     = $this->userServices->getUser();
            $directory  = 'divers';

            switch (true) {
                case $object instanceof Profile:
                    $directory = 'profile';
                    break;
                case $object instanceof Pathology:
                    $directory = 'pathology';
                    break;

                case $object instanceof Medication:
                    $directory = 'medication';
                    break;

                default:
                    $directory = 'divers';
            }

            $fs = new Filesystem();
            try {
                $fs->mkdir( '%kernel.root_dir%/../member/zne/' . $userId->getAuthZne() . '/' . $directory . '/'  );
            } catch (IOExceptionInterface $e) {
                echo "An error occurred while creating your directory at ".$e->getPath();
            }

            return $userId->getAuthZne() . '/' . $directory . '/';
        }        
    }
```
MY type : 
```
.......
            ->add("imageName", null, array(
                'required' => false,
                "label"         =>"medication.form.imgNom.name",
                "attr"          => array(
                    'disabled' => 'disabled',
                ),
            ))

            ->add("imageFile", VichImageType::class , [
                'required' => false,
                'allow_delete' => true, // not mandatory, default is true
                'download_link' => true, // not mandatory, default is true
                "label"   => "Scanne",
                "attr"          => array(
                    'class' => 'form-control',
                ),
            ])
......
```

**Comment by garak** [comment] 2017-03-09 09:32
Please don't comment on closed issues, open a new one
