### ISSUE TITLE
Web profiler template missing

### ISSUE THREAD

**Issue by BlackWiCKED** [dustin10/VichUploaderBundle#1070] opened 2019-12-09 09:13 UTC
### BC Break Report

My web profiler toolbar won't load and having the following records in the log:

> [2019-12-09 10:01:35] request.CRITICAL: Uncaught PHP Exception UnexpectedValueException: "The profiler template "@VichUploader/Collector/mapping_collector.html.twig" for data collector "vich_uploader.mapping_collector" does not exist." at /vendor/symfony/web-profiler-bundle/Profiler/TemplateManager.php line 89 {"exception":"[object] (UnexpectedValueException(code: 0): The profiler template \"@VichUploader/Collector/mapping_collector.html.twig\" for data collector \"vich_uploader.mapping_collector\" does not exist. at /vendor/symfony/web-profiler-bundle/Profiler/TemplateManager.php:89)"} []

Possibly related to: #1067 

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.12.1

#### Summary

Looks like the profiler can't find the required template.

#### Previous behavior

The profiler toolbar loaded correctly.

#### Current behavior

The profiler toolbar says: "An error occurred while loading the web debug toolbar."

#### How to reproduce

Enable the web profiler bundle and show the toolbar while having the latest version of VichUploaderBundle.

**EDIT:** Symfony 4.4.1 (env: dev, debug: true)

**Comment by garak** [comment] 2019-12-09 09:14
Symfony version?

**Comment by BlackWiCKED** [comment] 2019-12-09 09:18
Sorry, Symfony 4.4.1 (env: dev, debug: true)

**Comment by garak** [comment] 2019-12-09 09:21
Sorry, I can't reproduce

**Comment by BlackWiCKED** [comment] 2019-12-09 09:29
Works properly with VichUploaderBundle version 1.11.0. But when I upgrade to 1.12.1 the debug toolbar won't load, and the above mentioned log entry is being created.

Can you confirm that you enabled and see the profiler toolbar correctly?

**Comment by garak** [comment] 2019-12-09 09:32
![Schermata da 2019-12-09 10-32-22](https://user-images.githubusercontent.com/179866/70424189-3d475b00-1a6f-11ea-97c5-163bdf25d8cd.png)

**Comment by BlackWiCKED** [comment] 2019-12-09 09:34
My local config in **/config/packages/dev/web_profiler.yaml**
```
web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }
```

**Comment by garak** [comment] 2019-12-09 09:35
You can remove `intercept_redirects: false` (it's deprecated), but it's fine

**Comment by BlackWiCKED** [comment] 2019-12-09 09:40
Using PHP 7.3.11, but that's probably does not matters. Removed the intercept_redirects line but no difference. Here is what I see:

![Screenshot from 2019-12-09 10-36-39](https://user-images.githubusercontent.com/3763838/70424711-19d0e000-1a70-11ea-87f6-5d056293e03a.png)

Anyways, if no one can reproduce it, I will stick to the previous version until I find out what causing the trouble.

**Comment by garak** [comment] 2019-12-09 09:42
It's weird, these are changes between versions, I can't spot anything related to profiler:

https://github.com/dustin10/VichUploaderBundle/compare/1.11.0...1.12.1

**Comment by BlackWiCKED** [comment] 2019-12-09 10:05
My suspicion is that it has to do something with moving config files out from Resources folder. Maybe a relative path was used somewhere to define the template and this move made the path inaccessible. The only thing that bothers me is why I'm the only one affected. I don't remember configuring anything differently regarding the profiler, but eventually will find out. Maybe somebody else will report it too, we'll know more then. Thanks for your time to looking into it!

**Comment by garak** [comment] 2019-12-09 10:45
That config files are meant for others bundle to be configured with VichUploaderBundle, not for VichUploaderBundle itself

**Comment by BlackWiCKED** [comment] 2019-12-09 14:20
One addition to the above, it's not just the toolbar that crashed. Here is another error message I see on the pages where I have VichUploader installed.

> [2019-12-09 15:06:31] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "There are no registered paths for namespace "VichUploader"." at /vendor/easycorp/easyadmin-bundle/src/Resources/views/default/includes/_delete_form.html.twig line 2 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): There are no registered paths for namespace \"VichUploader\". at /vendor/easycorp/easyadmin-bundle/src/Resources/views/default/includes/_delete_form.html.twig:2)"} []

It's a returning element that might be the key to solve this mistery; ***No registered paths for namespace VichUploader***. I also noticed in my IDE that while using version 1.11.0 and pressing @ the hinting dropdown suggests @VichUploader (and the files in the bundle) while in the new version that's not the case. Like the bundle is not aware of some files, it does not registers those classes properly. This explains some things though, the problem appears when something referencing to @VichUploader namespace (Web profiler, EasyAdminBundle, etc...) They won't find what they are looking for. Might be a composer thing? Again, I have no clue why it's just me...

**Comment by gharlan** [comment] 2019-12-09 14:36
I can confirm the issue, 1.11 is working, 1.12 not. Same error. Sf 4.4.1

**Comment by BlackWiCKED** [comment] 2019-12-09 14:50
Workaround; if you register the namespace yourself it seems to be working. I had to add the following line to my projects config:

**config/packages/twig.yaml**
```
twig:
    paths:
        '%kernel.project_dir%/vendor/vich/uploader-bundle/templates': VichUploader
```
I'm sure this can be done in the vendor bundle as well, so users don't have to do it manually.

**Comment by garak** [comment] 2019-12-09 14:56
I just created an empty project with Symfony 4.4 (starting from website-skeleton), installed bundle and configured a mapped entity.
It just works as expected, without any further Twig configuration.

**Comment by gharlan** [comment] 2019-12-09 16:03
Found the issue on my side: because of another lib, some symfony bundles weren't updated to 4.4, especially the framework-bundle and twig-bundle :/

Now all bundles are 4.4 and it works with 1.12!

**Comment by garak** [comment] 2019-12-09 16:04
That's likely the same problem for other users.
I'm closing this, if someone has a valid way to reproduce problem, feel free to re-open

**Closed by garak** 2019-12-09 16:04 UTC
Labels: Support

**Comment by BlackWiCKED** [comment] 2019-12-09 16:17
Thank you @gharlan, that was it. I had symfony/validator package set to 4.3. It kept back some other packages from updating, so when I did a manual update, the issue was solved. Here is the log for the reference, one (ore more) of this caused the issue:

```
  - Updating symfony/service-contracts (v1.1.8 => v2.0.1): Loading from cache
  - Updating symfony/security-bundle (v4.3.9 => v4.4.1): Loading from cache
  - Updating symfony/translation-contracts (v1.1.7 => v2.0.1): Loading from cache
  - Updating symfony/validator (v4.3.0 => v4.4.1): Loading from cache
  - Updating symfony/twig-bundle (v4.3.9 => v4.4.1): Loading from cache
  - Updating symfony/framework-bundle (v4.3.9 => v4.4.1): Loading from cache
  - Updating symfony/web-profiler-bundle (v4.3.9 => v4.4.1): Loading from cache
  - Updating symfony/doctrine-bridge (v4.3.9 => v4.4.1): Loading from cache
```
@garak Please consider update the project dependencies reflecting to this, that would make sure nobody gets into this situation again.

**Comment by garak** [comment] 2019-12-09 16:22
I don't think requiring components we don't actually use is a good idea.
A better solution could be adding a note in documentation to warn users about this possible problem.

**Comment by grekpg** [comment] 2020-02-28 09:18
same error in version": "1.13.1", back to  "version": "1.11.0" fix error 
Symfony 4.3
