### ISSUE TITLE
Travis and runTests.sh should test the same

### ISSUE THREAD

**Issue by JHGitty** [dustin10/VichUploaderBundle#508] opened 2016-01-20 14:22 UTC
Thanks to @geekdevs I found this issue. (https://github.com/dustin10/VichUploaderBundle/issues/489#issuecomment-171189911)

Currently in Travis we do **not** test on Symfony versions ``2.5.0`` and ``2.6.0``. But in ``runTests.sh`` we test against these Symfony versions. Version ``2.4.0`` is missing in both tests.

There are 2 possible solutions:

1. We do no longer test against these Symfony versions because they are End-of-Life since 07/2015 and 01/2016. http://symfony.com/doc/current/contributing/community/releases.html#schedule

2. We add ``2.5.0`` and ``2.6.0`` to Travis and ``2.4.0`` to both.

What do you think?

**Comment by JHGitty** [comment] 2016-01-20 14:45
@K-Phoen What do you think should we do?

**Comment by K-Phoen** [comment] 2016-01-20 14:49
We are supposed to support `~2.3|~3.0`, or at least that's what our `composer.json` says. So in my opinion we should fix the bundle for the broken versions and add at least one entry for `~2.4`, `~2.5` and `~2.6` in the `.travis.yml` file.

I know that these versions are not supported anymore by the Symfony core team, but ideally I'd like this bundle to work seamlessly from Symfony ~2.3 to ~3.0.

Would you like to take the lead on this issue?

**Comment by JHGitty** [comment] 2016-01-20 14:57
@K-Phoen I agree with you. The ``composer.json`` file is the most important reason why we should check against all Symfony versions.

I'll create a Pull Request for Travis. Maybe we will find some BC breaks / broken tests. Hopefully Travis will run the tests successfully.

**Comment by geekdevs** [comment] 2016-01-20 14:59
Note that the problem is not only that `runTests.sh` tests different versions than travis, but also that `runTests.sh` fails on the versions which travis does not.

**Comment by garak** [comment] 2016-02-08 14:12
:-1:  for supporting unsupported versions of Symfony.
You could find yourself into a situation where your software is failing for a problem caused by Symfony and you cannot make Symfony fix that problem.
So you're not really supporting such versions, in the end.

**Comment by K-Phoen** [comment] 2016-02-11 09:35
I don't know yet what I want to do for the 1.0 release.

The `composer.json` files indicates that the bundle supports from Symfony ~2.3 to ~3.0. We are basically saying that the bundle works with Symfony 2.3, 2.4, 2.5, … up to 3.0. So including these versions in our test matrix kind of make sense (even if they are not maintained anymore).
That induces a longer run-time for our test builds and more maintenance-related work.

On the other hand, Symfony 2.3 is supposed to be compatible to 2.8 (at least according to semver). We know that it's not exactly that easy but well. So testing against 2.3, 2.8 and 3.0 should be enough.
The build will be smaller and there also will be less maintenance-related work, but we can not be sure that we really support all the versions that we claim support for.

Another possible *solution* : given the very slow evolution rate of this bundle, we could raise the minimal supported Symfony version to 2.7 (next LTS after 2.3).

WDYT?

**Comment by garak** [comment] 2016-02-11 10:03
I think that you should support every supported version of your dependencies, and nothing more.
So, you should support Symfony 2.3, 2.7, 2.8, 3.0 and test only for these versions.
Every "middle" version (I mean every version covered by semver but not supported, in this case Symfony 2.4, 2.5, 2.6) should be tolerated, but not actively supported.
Also, cutting support for a currently supported Symfony version is not fair. You should support Symfony 2.3 until May 2016.
Future releases will adapt, e.g. VichUploaderBundle 1.1 will support only 2.7/2.8./3.0 (and possibly new versions like 3.1 etc.)

**Comment by javiereguiluz** [comment] 2016-02-11 10:09
I agree with @garak and I'm doing the same in other bundle: support only 2.3, 2.7, 2.8, 3.0 and drop 2.3 support in May 2016.

**Comment by K-Phoen** [comment] 2016-02-11 10:21
Yeah, I thought of doing that : tolerating the "middle" versions without actively maintaining them. But I have to say that I'm not really comfortable with that. What if a user creates a new issue saying that he has a bug with a *tolerated* version of symfony? We should just tell him to upgrade to a supported version of Symfony or to deal with it himself?

In the end I'll think I'll go with this solution, but I'm not entirely satisfied :)

As for dropping support for 2.3, I was just suggesting it *almost* as a joke. I'd really like to see some statistics about versions usage though.

> You should support Symfony 2.3 until May 2016.
> Future releases will adapt, e.g. VichUploaderBundle 1.1 will support only 2.7/2.8./3.0 (and possibly new versions like 3.1 etc.)

Not being able to work as much as I'd like on this bundle (lack of free time, …), I won't make such strong assertions :)
I hope you understand why ;)

So :
* supported (and tested) versions: 2.3, 2.7, 2.8, 3.0
* tolerated versions: all the non-LTS since 2.3

Everybody agrees?

**Comment by garak** [comment] 2016-02-11 10:26
I think that the purpose of supported versions is just that: telling to an user complaining about a bug that he/she is supposed to upgrade.
About lack of time: it's a common problem :wink: that you can mitigate by assigning collaborators (take this as a volunteering offer)

**Comment by K-Phoen** [comment] 2016-02-15 10:16
I fixed the `runTests.sh` file and wrote a [few comments](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/symfony_support_policy.md) on our support policy concerning Symfony versions.

@dustin10 could you give me the admin rights on this repo? So I can configure myself the collaborators and stuff like that :)

**Comment by K-Phoen** [comment] 2016-02-15 10:16
And since the `runTests.sh` scripts now works and that our support policy is defined, I close this issue.

**Closed by K-Phoen** 2016-02-15 10:16 UTC
Labels: Bug

**Comment by dustin10** [comment] 2016-02-22 15:58
@K-Phoen I think there are only collaborators and one admin (me).
