### ISSUE TITLE
Fix DEPRECATED logs generate by Symfony 6.3

### ISSUE THREAD

**Issue by JoDarma-lp** [dustin10/VichUploaderBundle#1399] opened 2023-08-04 18:38 UTC
`Registering \"Vich\\UploaderBundle\\EventListener\\Doctrine\\RemoveListener\" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute`
`Registering \"Vich\\UploaderBundle\\EventListener\\Doctrine\\UploadListener\" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute`
`Registering \"Vich\\UploaderBundle\\EventListener\\Doctrine\\CleanListener\" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute. `
`Registering \"Vich\\UploaderBundle\\EventListener\\Doctrine\\RemoveListener\" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute`
`Registering \"Vich\\UploaderBundle\\EventListener\\Doctrine\\UploadListener\" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute
`

You should to update the code to use new attribute #[AsDoctrineListener] to avoir Symfony deprecated message when using your Bundle.

**Comment by garak** [comment] 2023-08-04 20:38
Duplicate of #1388

**Closed by garak** 2023-08-04 20:38 UTC

**Comment by JoDarma-lp** [comment] 2023-08-04 20:57
Yep, but deprecated message are always logs #1391 doesn't totally fix the deprecated message

**Comment by mdriessen** [comment] 2023-08-09 11:20
@garak Do you have any timeline for tagging a new release with these fixes?

**Comment by JoDarma-lp** [comment] 2023-08-09 16:02
I'm working on Symfony 6.3 and `"vich/uploader-bundle": "2.1.1"` and the deprecations still here.

How you turn on dev-master version ?

**Comment by mdriessen** [comment] 2023-08-09 16:14
Use `"vich/uploader-bundle": "^2.1@dev"` and run `composer update vich/uploader-bundle`.

The deprecation `Method getEntityManager() is deprecated and will be removed in Doctrine ORM 3.0. Use getObjectManager() instead.` still exists. But that's only when removing a file. The above deprecation triggers 4 times per request.

**Comment by endelwar** [comment] 2023-08-09 20:03
I can confirm no more 
`User Deprecated: Since symfony/doctrine-bridge 6.3: Registering "Vich\UploaderBundle\EventListener\Doctrine\UploadListener" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute.` 

on Symfony 6.3.2 with

`"vich/uploader-bundle": "dev-master"`

**Comment by laurentmuller** [comment] 2023-08-10 08:43
I have tested with Symfony 6.3.3 and the only remaining deprecation is:

`User Deprecated: Method Doctrine\ORM\Event\LifecycleEventArgs::getEntityManager() is deprecated and will be removed in Doctrine ORM 3.0. Use getObjectManager() instead.`

It is explained in #1393 and resolved in #1395.

**Comment by laurentmuller** [comment] 2023-08-10 08:57
We can use the `#[AsDoctrineListener]` attribute but then all listeners are registred even if the user does not require one.
See the `registerListeners` method on the `VichUploaderExtension` class.

**Comment by mdriessen** [comment] 2023-08-10 09:47
Any reason #1395 was closed without being merged?

**Comment by garak** [comment] 2023-08-10 09:58
> Any reason #1395 was closed without being merged?

It was closed by PR author himself

**Comment by laurentmuller** [comment] 2023-08-10 10:28
This was a mistake from me. I have re-opened.

Sorry...
