### ISSUE TITLE
 Catchable Fatal Error: Argument 2 passed to Vich\UploaderBundle\Metadata\Driver\YamlDriver::guessClassName() must be of the type array, string given,   called in /Users/uthopiko/Developer/agenda/vendor/vich/uploader-bundle/Metadata/Driver/YamlDriver.php on line 40 and defined

### ISSUE THREAD

**Issue by uthopiko** [dustin10/VichUploaderBundle#490] opened 2016-01-02 08:29 UTC
I am trying to use VichUpload but i have a problem with configuration. When i execute doctrine:schema:update throws me the following error. 
```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 2 passed to Vich\UploaderBundle\Metadata\Driver\YamlDriver::guessClassName() must be of the type array, string given,
  called in /Users/uthopiko/Developer/agenda/vendor/vich/uploader-bundle/Metadata/Driver/YamlDriver.php on line 40 and defined. 
```
I am using SF3. The configuration is:

```AppBundle\Entity\Concert:
    type: entity
    table: concert
    indexes:
        group_id:
            columns:
                - group_id
        municipio_id:
            columns:
                - municipio_id
        register_id:
            columns:
                - register_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: datetime
            nullable: false
        normalImage: string
    manyToOne:
        group:
            targetEntity: MusicGroup
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: id
            orphanRemoval: false
        municipio:
            targetEntity: Municipios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                municipio_id:
                    referencedColumnName: id
            orphanRemoval: false
        register:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                register_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
```

```
<?php

namespace AppBundle\Entity;

/**
 * Concert
 */
class Concert
{
 ....
    /**
     * @var string
     */
    protected $normalImage;

    /**
     * @var File $image
     */
    protected $image;
....
    /**
     * Set normalImage
     *
     * @param string $normalImage
     * @return Image
     */
    public function setNormalImage($normalImage)
    {
        $this->normalImage = $normalImage;
        return $this;
    }
    /**
     * Get normalImage
     *
     * @return string
     */
    public function getNormalImage()
    {
        return $this->normalImage;
    }
    public function setImage(File $image = null)
    {
        $this->image = $image;
        return $this;
    }
    public function getImage()
    {
        return $this->image;
    }
 ...
}
```
```AppBundle\Entity\Concert:
    image:
        mapping:           concert
        filename_property: normal_image```

```
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
            concert:
                uri_prefix:         /images/concert
                upload_destination: %kernel.root_dir%/../web/images/concert 
```

**Comment by garak** [comment] 2016-01-12 13:26
I just tried you mapping and I can't reproduce your error: updating the schema is working, I get the table in mysql.
Tried with Symfony 3.0.1 and VichUploaderBundle dev-master (just installed the bundle in Symfony standard edition)

**Comment by JHGitty** [comment] 2016-01-20 13:57
Cannot reproduce this issue with Symfony 3. I think we should remove the milestone from this issue until it is reproducible.

**Comment by jacmba** [comment] 2016-02-04 08:13
No news yet?

I'm having the same issue with Symfony 3.0.2.

**Comment by JHGitty** [comment] 2016-02-04 10:10
@jacmba Could you explain how to reproduce this issue?
Will it be fixed with this commit? https://github.com/visionappscz/VichUploaderBundle/commit/ff2fa995194a7417cec08bc7c395f3317bd7245a

**Comment by mbohal** [comment] 2016-02-05 15:27
@JHGitty Im the author of the linked commit. Should I submit a PR?

**Comment by JarJak** [comment] 2016-02-06 22:53
Sare problem here, Symfony 3.0.2. @mbohal submit PR please.

**Comment by JHGitty** [comment] 2016-02-07 15:02
@mbohal As @JarJak confirmed your fix works. So please submit a PR.

**Comment by mbohal** [comment] 2016-02-08 09:10
PR is here: https://github.com/dustin10/VichUploaderBundle/pull/526

**Comment by K-Phoen** [comment] 2016-02-08 14:04
Should be fixed now.

**Closed by K-Phoen** 2016-02-08 14:04 UTC
