### ISSUE TITLE
How have Image_id for change the name ?

### ISSUE THREAD

**Issue by razbounak** [dustin10/VichUploaderBundle#731] opened 2017-06-25 12:52 UTC
Hello,

I have a custom namer and I want have the future id of my image for change the name.

`
    public function name($object, PropertyMapping $mapping)
    {
        $productId = $object->getProduct()->getId();
        $file = $object->getImageFile();
        $extension = $file->getExtension();

       // Here
        $imageId = ?;

        return $productId . '-' . $imageId  . '.' . $extension;
    }
`

Thanks for your help

**Comment by garak** [comment] 2017-06-25 16:28
Duplicate of #14

**Closed by garak** 2017-06-25 16:28 UTC

**Comment by Koc** [comment] 2017-06-25 19:41
Use hash namer :)
