### ISSUE TITLE
Custom DirectoryName, object->getId() returns null on creating entity

### ISSUE THREAD

**Issue by vasoft** [dustin10/VichUploaderBundle#473] opened 2015-11-22 14:02 UTC
I need to create a custom directoryName like this "/object->id/filename". When I create a new entity, because it is not yet in the DB, $object->getId() returns null. Do you have any suggestion how can I solve this? Thank you!

    public function directoryName($object, PropertyMapping $mapping){

        $dirName = $object->getId();
        
        return $dirName;
    }

**Comment by K-Phoen** [comment] 2015-11-22 22:24
That's a *known issue* (to be exact, it's more a *won't fix*).

The directory and file name are computed **before** the entity is actually saved, so for new objects the identifier is unavailable. By design, there is nothing that can be done to avoid this… except if you don't use auto-incremented identifiers but generated ones (UUIDs for instance).

I close this issue as it won't be fixed (there is nothing to be fixed) but do not hesitate to ask more questions if you need :)

**Closed by K-Phoen** 2015-11-22 22:24 UTC
Labels: Support

**Comment by webdevilopers** [comment] 2016-01-01 15:25
Did you find any workaround @vasoft ?

**Comment by gnutix** [comment] 2019-08-12 17:56
I painfully discovered this won't fix and had no choice but to keep pushing, and be damn the slight performance drawback. Here's the result for those who might want to go down the same path to hell : https://gist.github.com/gnutix/e79225389ed470b3ca026274e7b8261b
